In [168]:
import pandas as pd
import numpy as np

In [169]:
import sklearn

In [170]:
from sklearn.datasets import load_breast_cancer
X,y = load_breast_cancer(return_X_y=True,as_frame=True)
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

## Q3.

In [171]:
X.shape

(569, 30)

In [172]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

## Q4.

In [173]:
y.unique()

array([0, 1])

## Q5.

In [174]:
y[y==0]

0      0
1      0
2      0
3      0
4      0
      ..
563    0
564    0
565    0
566    0
567    0
Name: target, Length: 212, dtype: int64

## Q6.

In [175]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

## Q7.

In [176]:
X.corr()

mean radius  mean texture  mean perimeter  mean area  \
mean radius                 1.000000      0.323782        0.997855   0.987357   
mean texture                0.323782      1.000000        0.329533   0.321086   
mean perimeter              0.997855      0.329533        1.000000   0.986507   
mean area                   0.987357      0.321086        0.986507   1.000000   
mean smoothness             0.170581     -0.023389        0.207278   0.177028   
mean compactness            0.506124      0.236702        0.556936   0.498502   
mean concavity              0.676764      0.302418        0.716136   0.685983   
mean concave points         0.822529      0.293464        0.850977   0.823269   
mean symmetry               0.147741      0.071401        0.183027   0.151293   
mean fractal dimension     -0.311631     -0.076437       -0.261477  -0.283110   
radius error                0.679090      0.275869        0.691765   0.732562   
texture error              -0.097317      0.386358       -0.086761  -0.066280   
perimeter error             0.674172      0.281673        0.693135   0.726628   
area error                  0.735864      0.259845        0.744983   0.800086   
smoothness error           -0.222600      0.006614       -0.202694  -0.166777   
compactness error           0.206000      0.191975        0.250744   0.212583   
concavity error             0.194204      0.143293        0.228082   0.207660   
concave points error        0.376169      0.163851        0.407217   0.372320   
symmetry error             -0.104321      0.009127       -0.081629  -0.072497   
fractal dimension error    -0.042641      0.054458       -0.005523  -0.019887   
worst radius                0.969539      0.352573        0.969476   0.962746   
worst texture               0.297008      0.912045        0.303038   0.287489   
worst perimeter             0.965137      0.358040        0.970387   0.959120   
worst area                  0.941082      0.343546        0.941550   0.959213   
worst smoothness            0.119616      0.077503        0.150549   0.123523   
worst compactness           0.413463      0.277830        0.455774   0.390410   
worst concavity             0.526911      0.301025        0.563879   0.512606   
worst concave points        0.744214      0.295316        0.771241   0.722017   
worst symmetry              0.163953      0.105008        0.189115   0.143570   
worst fractal dimension     0.007066      0.119205        0.051019   0.003738   

                         mean smoothness  mean compactness  mean concavity  \
mean radius                     0.170581          0.506124        0.676764   
mean texture                   -0.023389          0.236702        0.302418   
mean perimeter                  0.207278          0.556936        0.716136   
mean area                       0.177028          0.498502        0.685983   
mean smoothness                 1.000000          0.659123        0.521984   
mean compactness                0.659123          1.000000        0.883121   
mean concavity                  0.521984          0.883121        1.000000   
mean concave points             0.553695          0.831135        0.921391   
mean symmetry                   0.557775          0.602641        0.500667   
mean fractal dimension          0.584792          0.565369        0.336783   
radius error                    0.301467          0.497473        0.631925   
texture error                   0.068406          0.046205        0.076218   
perimeter error                 0.296092          0.548905        0.660391   
area error                      0.246552          0.455653        0.617427   
smoothness error                0.332375          0.135299        0.098564   
compactness error               0.318943          0.738722        0.670279   
concavity error                 0.248396          0.570517        0.691270   
concave points error            0.380676          0.642262        0.683260   
symmetry error                 

In [177]:
M = [[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]]

In [178]:
Mdf = pd.DataFrame(M)

In [179]:
Mdf

0     1     2
0   7.0  16.0  31.0
1   NaN   NaN  66.0
2  12.0   5.0   NaN
3  98.0   NaN  92.0

In [180]:
from sklearn.impute import SimpleImputer

In [181]:
?SimpleImputer

In [182]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

## Q8.

In [183]:
impM = imp.fit_transform(Mdf)
impM

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [184]:
from sklearn.preprocessing import FunctionTransformer

In [185]:
?FunctionTransformer

In [186]:
ft = FunctionTransformer(np.log10)

In [187]:
ftx = pd.DataFrame([[1, 1], [2, 3],[10,100]])
ftx

0    1
0   1    1
1   2    3
2  10  100

In [188]:
ft.fit(ftx)

FunctionTransformer(func=<ufunc 'log10'>)

## Q9.

In [189]:
ftxt = ft.transform(ftx)
ftxt

0         1
0  0.00000  0.000000
1  0.30103  0.477121
2  1.00000  2.000000

In [190]:
irisdf = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', names=['sepal length', 'sepal width', 'petal length', 'petal width','label'])
irisdf

sepal length  sepal width  petal length  petal width           label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [191]:
from sklearn.preprocessing import PolynomialFeatures

In [192]:
pf = PolynomialFeatures(degree=2)

In [193]:
irisdft = pf.fit_transform(irisdf.drop(['label'], axis=1))
irisdft

array([[ 1.  ,  5.1 ,  3.5 , ...,  1.96,  0.28,  0.04],
       [ 1.  ,  4.9 ,  3.  , ...,  1.96,  0.28,  0.04],
       [ 1.  ,  4.7 ,  3.2 , ...,  1.69,  0.26,  0.04],
       ...,
       [ 1.  ,  6.5 ,  3.  , ..., 27.04, 10.4 ,  4.  ],
       [ 1.  ,  6.2 ,  3.4 , ..., 29.16, 12.42,  5.29],
       [ 1.  ,  5.9 ,  3.  , ..., 26.01,  9.18,  3.24]])

## Q10.

In [194]:
irisdft.shape

(150, 15)

In [195]:
from sklearn.datasets import fetch_california_housing
X,y = fetch_california_housing(return_X_y=True, as_frame=True)
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [196]:
from sklearn.feature_selection import SelectPercentile, mutual_info_regression

In [197]:
?SelectPercentile

In [198]:
X_ch_t = SelectPercentile(mutual_info_regression, percentile=10).fit_transform(X, y)

## Q11.

In [199]:
X_ch_t.shape

(20640, 1)

In [200]:
arr = np.array(X)

In [201]:
arr[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

## Q 12.

In [202]:
ntrain = arr[:int((4/5)*len(arr))]
nytrain = y[:int((4/5)*len(arr))]
ntest = arr[int((4/5)*len(arr)):]
nytest = y[int((4/5)*len(arr)):]
ntrain.shape

(16512, 8)

In [203]:
from sklearn.metrics import r2_score

In [204]:
y_mean = nytrain.mean()

In [205]:
y_pred = np.full_like(nytrain, y_mean)

In [206]:
y_pred

array([2.02067031, 2.02067031, 2.02067031, ..., 2.02067031, 2.02067031,
       2.02067031])

## Q13. Wrong options

In [207]:
r2 = r2_score(nytrain, y_pred)
r2

0.0

In [208]:
from sklearn.linear_model import SGDRegressor

In [209]:
?SGDRegressor


In [210]:
from sklearn.preprocessing import MinMaxScaler

In [211]:
?MinMaxScaler

In [212]:
scaler = MinMaxScaler()

In [213]:
Xs = scaler.fit_transform(ntrain)

In [214]:
Xs

array([[0.53966842, 0.78431373, 0.0435123 , ..., 0.00311048, 0.5674814 ,
        0.21115538],
       [0.53802706, 0.39215686, 0.03822395, ..., 0.00236641, 0.565356  ,
        0.21215139],
       [0.46602805, 1.        , 0.05275646, ..., 0.00352233, 0.5642933 ,
        0.21015936],
       ...,
       [0.25402408, 0.41176471, 0.04053565, ..., 0.00410894, 0.55472901,
        0.32270916],
       [0.20294203, 0.11764706, 0.03239859, ..., 0.00432862, 0.55154091,
        0.31772908],
       [0.20006621, 0.41176471, 0.03805876, ..., 0.00436051, 0.55472901,
        0.30876494]])

In [215]:
sgd = SGDRegressor()

In [216]:
sgd.fit(ntrain,nytrain)

SGDRegressor()

In [217]:
from sklearn.metrics import mean_squared_error

## Q14. incorrect

In [218]:
score = mean_squared_error(nytrain, sgd.predict(Xs))
score

7.712101815431717e+21

In [219]:
Xts = scaler.transform(ntest)

## Q15. in correct

In [220]:
tscore = mean_squared_error(nytest, sgd.predict(Xts))
tscore

1.328549717401579e+22

In [221]:
from sklearn.model_selection import KFold

In [222]:
?KFold

In [223]:
from sklearn.model_selection import cross_val_score

In [224]:
?cross_val_score

In [225]:
from sklearn.linear_model import LinearRegression

In [226]:
kf = KFold(n_splits=5)

## Q16.

In [227]:
cross_val_score(LinearRegression(), X, y, cv=5)

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

In [228]:
from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True,as_frame=True)
X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

## Q17.

In [229]:
X.shape

(442, 10)

In [230]:
from sklearn.model_selection import train_test_split

In [231]:
?train_test_split

In [232]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [233]:
from sklearn.preprocessing import StandardScaler

In [234]:
?StandardScaler

In [235]:
scaler = StandardScaler()

In [236]:
X_train_s = scaler.fit_transform(X_train)
X_train_s

array([[ 0.10074167, -0.95837272,  1.27363398, ...,  1.02417833,
        -0.10757477, -0.64420338],
       [-0.58607437, -0.95837272,  1.71607781, ...,  0.03673346,
        -0.62937444,  0.74187688],
       [ 0.17705456, -0.95837272, -0.54271439, ..., -0.08574032,
        -0.46170682,  0.13546677],
       ...,
       [-1.12026462,  1.04343538, -0.40299528, ...,  2.21064309,
         0.72305661, -0.90409343],
       [-0.12819701,  1.04343538, -0.19341663, ..., -0.08574032,
         1.64128117,  0.13546677],
       [-0.73870016,  1.04343538, -0.56600091, ..., -0.35365172,
         0.28509075,  0.8285069 ]])

In [237]:
lr = LinearRegression()

In [238]:
lr.fit(X_train_s,y_train)

LinearRegression()

In [239]:
X_test_s = scaler.transform(X_test)

In [240]:
pred = lr.predict(X_test_s)

In [241]:
from sklearn.metrics import r2_score

## Q 18.

In [242]:
r2_score(y_test, pred)

0.5341988244945843

In [243]:
lr.coef_

array([ -0.1850394 , -10.74378586,  23.97110665,  15.4460079 ,
       -33.6348803 ,  19.07653925,   3.87696491,  10.51802947,
        34.1537076 ,   1.91366485])

## Q19.

In [244]:
pd.DataFrame({'variable': X.columns, 'estimate': lr.coef_})

variable   estimate
0      age  -0.185039
1      sex -10.743786
2      bmi  23.971107
3       bp  15.446008
4       s1 -33.634880
5       s2  19.076539
6       s3   3.876965
7       s4  10.518029
8       s5  34.153708
9       s6   1.913665

In [245]:
from sklearn.linear_model import RidgeCV

In [246]:
?RidgeCV

In [247]:
rcv = RidgeCV(alphas=np.logspace(-4,0,num=20), cv=5, scoring='neg_mean_absolute_error')

In [248]:
rcv.fit(X_train_s, y_train)

RidgeCV(alphas=array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00]),
        cv=5, scoring='neg_mean_absolute_error')

In [249]:
from sklearn.metrics import mean_absolute_error

## Q20.

In [250]:
mean_absolute_error(y_train, rcv.predict(X_train_s))

43.47104306293406